name: 'Pull Request'
on:
  pull_request:
    branches:
      - master

jobs:
  pull_request:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Java Setup
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: gradle build
        run: gradle clean build test

      - name: snyk-scan
        uses: snyk/actions/gradle@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --org=dwp-dataworks --severity-threshold=high
