name: High vulns Snyk PR scan

on: pull_request

env:
  IMAGE_NAME: dwpdigital/example

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gradle Build Jar
        id: gradle-build
        run: ./gradlew build
      - name: Upload jar
        uses: actions/upload-artifact@v1
        with:
          name: gradle-build
          path: build/libs/*.jar

  docker-build-and-scan:
    runs-on: ubuntu-latest
    needs: gradle-build
    steps:
      - uses: actions/checkout@v2
      - name: Download jar
        uses: actions/download-artifact@v1
        with:
          name: gradle-build
      - shell: bash
        run: |
          mkdir -p build/libs
          cp gradle-build/*.jar build/libs/
      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:latest .
      - name: Run Snyk to check image for high vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.IMAGE_NAME }}
          args: --file=Dockerfile --policy-path=./.snyk --severity-threshold=high --exclude-base-image-vulns --org=dwp-dataworks
